# 使用 docker-compose up -d
# 启动时需要将 .env 中的 localhost 改成 mongodb
version: "3"
services:
  app:
    container_name: auto-answer-backend
    restart: on-failure
    build: ./
    ports:
      - "3981:3981"
    # volumes:
    #   - .:/app
    depends_on:
      - mongodb
  mongodb:
    container_name: auto-answer-mongo
    image: mongo:4.0.8
    volumes: 
      - ~/mongo/db:/data/db
    ports:
      - "27017:27017"