name: docker

on:
  push:
    branches: [master] # master 分支有 push 时触发

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH
        uses: appleboy/ssh-action@master
        with:
          host: 139.9.212.113
          username: root
          password: ${{ secrets.PASS }}
          port: 22
          script: |
             cd /home/auto-answer-backend/
             git pull
             docker rm auto-answer-backend
             docker rm auto-answer-mongo
             docker-compose stop
             docker-compose rm -f
             docker-compose up -d